### ISSUE TITLE
Add README.md in js/

### ISSUE THREAD

**Issue by julen** [iafan/Plurr#4]
The lack of a *README.md* file in the *js/* directory (or more specifically, not having it side-by-side with *package.json*), makes npm to display [no relevant information for the library](https://www.npmjs.com/package/plurr).

I don't believe it's possible to re-publish a package that already exists in the registry, so I'm not sure there's a way to add a readme file without publishing a new version.

**Comment by iafan** [comment]
Added via 8bcbccea0d648a6bf9191e863b4a43a97f21c734
